/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_AckStatus_H_
#define	_AckStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AckStatus {
	AckStatus_accepted	= 0,
	AckStatus_rejected_unknown_toll_point	= 1,
	AckStatus_rejected_invalid_lane	= 2,
	AckStatus_rejected_unknown_vehicle	= 3,
	AckStatus_rejected_unknown_tam_seq	= 4,
	AckStatus_rejected_duplicate_tum	= 5,
	AckStatus_rejected_other	= 6
} e_AckStatus;

/* AckStatus */
typedef long	 AckStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AckStatus;
asn_struct_free_f AckStatus_free;
asn_struct_print_f AckStatus_print;
asn_constr_check_f AckStatus_constraint;
ber_type_decoder_f AckStatus_decode_ber;
der_type_encoder_f AckStatus_encode_der;
xer_type_decoder_f AckStatus_decode_xer;
xer_type_encoder_f AckStatus_encode_xer;
per_type_decoder_f AckStatus_decode_uper;
per_type_encoder_f AckStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AckStatus_H_ */
#include <asn_internal.h>
