/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_AmountCents_H_
#define	_AmountCents_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AmountCents */
typedef long	 AmountCents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AmountCents;
asn_struct_free_f AmountCents_free;
asn_struct_print_f AmountCents_print;
asn_constr_check_f AmountCents_constraint;
ber_type_decoder_f AmountCents_decode_ber;
der_type_encoder_f AmountCents_encode_der;
xer_type_decoder_f AmountCents_decode_xer;
xer_type_encoder_f AmountCents_encode_xer;
per_type_decoder_f AmountCents_decode_uper;
per_type_encoder_f AmountCents_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AmountCents_H_ */
#include <asn_internal.h>
