/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_MsgCount_H_
#define	_MsgCount_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MsgCount */
typedef long	 MsgCount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgCount;
asn_struct_free_f MsgCount_free;
asn_struct_print_f MsgCount_print;
asn_constr_check_f MsgCount_constraint;
ber_type_decoder_f MsgCount_decode_ber;
der_type_encoder_f MsgCount_encode_der;
xer_type_decoder_f MsgCount_decode_xer;
xer_type_encoder_f MsgCount_encode_xer;
per_type_decoder_f MsgCount_decode_uper;
per_type_encoder_f MsgCount_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgCount_H_ */
#include <asn_internal.h>
