/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_MsgCount;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneID;
extern struct asn_TYPE_descriptor_s asn_DEF_TumSeqNum;
extern struct asn_TYPE_descriptor_s asn_DEF_AmountCents;
extern struct asn_TYPE_descriptor_s asn_DEF_TollID;
extern struct asn_TYPE_descriptor_s asn_DEF_TollTimestamp;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleClass;
extern struct asn_TYPE_descriptor_s asn_DEF_AckStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_TollAdvertisementMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_TollUsageMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_TollUsageAckMessage;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module J3217-Toll-Messages in /workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn */
	&asn_DEF_MsgCount,	
	&asn_DEF_LaneID,	
	&asn_DEF_TumSeqNum,	
	&asn_DEF_AmountCents,	
	&asn_DEF_TollID,	
	&asn_DEF_TollTimestamp,	
	&asn_DEF_VehicleClass,	
	&asn_DEF_AckStatus,	
	&asn_DEF_TollAdvertisementMessage,	
	&asn_DEF_TollUsageMessage,	
	&asn_DEF_TollUsageAckMessage,	
	0
};

