/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_TollUsageMessage_H_
#define	_TollUsageMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TumSeqNum.h"
#include "MsgCount.h"
#include <VisibleString.h>
#include "VehicleClass.h"
#include <NativeInteger.h>
#include "TollID.h"
#include "LaneID.h"
#include "TollTimestamp.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TollUsageMessage */
typedef struct TollUsageMessage {
	TumSeqNum_t	 tumSequenceNum;
	MsgCount_t	 tamSequenceNum;
	VisibleString_t	 tempID;
	VehicleClass_t	 vehicleClass;
	long	 vehicleType;
	TollID_t	 tollPointID;
	TollID_t	 tollChargerID;
	LaneID_t	 laneID;
	TollTimestamp_t	 eventTimeUtc;
	long	 speedCmps;
	long	 latDeg1e7;
	long	 lonDeg1e7;
	OCTET_STRING_t	*tumHash	/* OPTIONAL */;
	VisibleString_t	*certificateId	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TollUsageMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollUsageMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _TollUsageMessage_H_ */
#include <asn_internal.h>
