/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_TollID_H_
#define	_TollID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TollID */
typedef VisibleString_t	 TollID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollID;
asn_struct_free_f TollID_free;
asn_struct_print_f TollID_print;
asn_constr_check_f TollID_constraint;
ber_type_decoder_f TollID_decode_ber;
der_type_encoder_f TollID_encode_der;
xer_type_decoder_f TollID_decode_xer;
xer_type_encoder_f TollID_encode_xer;
per_type_decoder_f TollID_decode_uper;
per_type_encoder_f TollID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollID_H_ */
#include <asn_internal.h>
