/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_TollAdvertisementMessage_H_
#define	_TollAdvertisementMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include <NativeInteger.h>
#include "TollID.h"
#include <VisibleString.h>
#include "TollTimestamp.h"
#include "AmountCents.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TollAdvertisementMessage */
typedef struct TollAdvertisementMessage {
	MsgCount_t	 msgCount;
	long	 protocolVersion;
	TollID_t	 tollPointID;
	TollID_t	 tollChargerID;
	VisibleString_t	*tollPointName	/* OPTIONAL */;
	TollTimestamp_t	 validFromUtc;
	TollTimestamp_t	 validUntilUtc;
	long	 broadcastIntervalMs;
	AmountCents_t	 ratePassengerCents;
	AmountCents_t	 rateHeavyVehicleCents;
	AmountCents_t	 rateBusCents;
	VisibleString_t	*certificateId	/* OPTIONAL */;
	OCTET_STRING_t	*signedData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TollAdvertisementMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollAdvertisementMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _TollAdvertisementMessage_H_ */
#include <asn_internal.h>
