/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_TollTimestamp_H_
#define	_TollTimestamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TollTimestamp */
typedef VisibleString_t	 TollTimestamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollTimestamp;
asn_struct_free_f TollTimestamp_free;
asn_struct_print_f TollTimestamp_print;
asn_constr_check_f TollTimestamp_constraint;
ber_type_decoder_f TollTimestamp_decode_ber;
der_type_encoder_f TollTimestamp_encode_der;
xer_type_decoder_f TollTimestamp_decode_xer;
xer_type_encoder_f TollTimestamp_encode_xer;
per_type_decoder_f TollTimestamp_decode_uper;
per_type_encoder_f TollTimestamp_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollTimestamp_H_ */
#include <asn_internal.h>
