/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_TollUsageAckMessage_H_
#define	_TollUsageAckMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include <VisibleString.h>
#include "TumSeqNum.h"
#include "TollID.h"
#include "AckStatus.h"
#include "AmountCents.h"
#include "TollTimestamp.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TollUsageAckMessage */
typedef struct TollUsageAckMessage {
	MsgCount_t	 msgCount;
	VisibleString_t	 tempID;
	TumSeqNum_t	 tumSequenceNum;
	TollID_t	 tollPointID;
	AckStatus_t	 ackStatus;
	VisibleString_t	*transactionID	/* OPTIONAL */;
	AmountCents_t	*amountCents	/* OPTIONAL */;
	TollTimestamp_t	 ackTimeUtc;
	OCTET_STRING_t	*signedTumHash	/* OPTIONAL */;
	VisibleString_t	*certificateId	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TollUsageAckMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollUsageAckMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _TollUsageAckMessage_H_ */
#include <asn_internal.h>
