/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "J3217-Toll-Messages"
 * 	found in "/workspace/src/v2i-hub/TollPlugin/asn1/J3217TollMessages.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -pdu=all`
 */

#ifndef	_VehicleClass_H_
#define	_VehicleClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleClass {
	VehicleClass_passenger_car	= 0,
	VehicleClass_heavy_vehicle	= 1,
	VehicleClass_bus	= 2,
	VehicleClass_unknown	= 3
} e_VehicleClass;

/* VehicleClass */
typedef long	 VehicleClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleClass;
asn_struct_free_f VehicleClass_free;
asn_struct_print_f VehicleClass_print;
asn_constr_check_f VehicleClass_constraint;
ber_type_decoder_f VehicleClass_decode_ber;
der_type_encoder_f VehicleClass_encode_der;
xer_type_decoder_f VehicleClass_decode_xer;
xer_type_encoder_f VehicleClass_encode_xer;
per_type_decoder_f VehicleClass_decode_uper;
per_type_encoder_f VehicleClass_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleClass_H_ */
#include <asn_internal.h>
